### PR TITLE
Add CSP when load file svg

### PR DESCRIPTION
**Pull request by noobpk**
Fix bug Stored XSS when add media file with format .svg allows for arbitrary execution of JavaScript
Disclosure: https://huntr.dev/bounties/500b0ee1-3fd7-4efc-861d-7082f2794745

### CODE REVIEW

**Comment by sdebacker** [comment]
In my opinion, the .htaccess should stay the same as that of Laravel. This doesn't give a solution for ngnix or other.
What about parsing and removing script tags in svg files during upload ?

**Comment by noobpk** [comment]
> In my opinion, the .htaccess should stay the same as that of Laravel. This doesn't give a solution for ngnix or other.
> What about parsing and removing script tags in svg files during upload ?

I find filtering script tags in other svg complicated and take a long time to process.
My recommendation is to use CSP or not for svg file upload.
For CSP you can not use .htaccess but create a new middleware to add CSP for the response

```
public function handle(Request $request, Closure $next)
    {
        $response = $next($request);
        $response->headers->set('Content-Security-Policy', "script-src" 'none'");
        return $response;
    }
```

**Comment by sdebacker** [comment]
The middleware solution sounds good, would you make a new PR?

**Comment by noobpk** [comment]
> The middleware solution sounds good, would you make a new PR?

Ok. I will update this PR now. No need to create a new PR. :D

**Comment by sdebacker** [comment]
I rather imagined this middelware in the [Core](https://github.com/TypiCMS/Core).

**Comment by noobpk** [comment]
> I rather imagined this middelware in the [Core](https://github.com/TypiCMS/Core).

Ah, I forgot this doesn't contain core .I will create a PR for core ^^!

**Comment by noobpk** [comment]
Well, Adding CSP through middleware affects the entire source code. I haven't figured out how to just add per .svg format. Looks like this is not very good ^^!!.

**Comment by noobpk** [comment]
I think we should remove the svg file from the upload file. :D

**Pull request closed without merging**
